# Generated by Django 3.1.1 on 2020-10-10 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201010_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='watchlist_users',
            field=models.ManyToManyField(blank=True, related_name='watchlist_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
