# Generated by Django 3.1.1 on 2020-10-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='seller',
            field=models.CharField(default='None', max_length=64),
        ),
    ]
