# Generated by Django 3.1.1 on 2020-10-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_item_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='seller',
            field=models.CharField(default='username', max_length=64),
        ),
    ]
