# Generated by Django 3.1.1 on 2020-10-11 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20201011_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='seller',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=64),
        ),
    ]
