# Generated by Django 3.1.1 on 2020-10-11 14:29

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20201011_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='seller',
            field=models.CharField(default=auctions.models.User, max_length=64),
        ),
    ]
